server: default

storage:
  mysql:
    host: localhost
    port: 3306
    # You should use a separate database for this plugin
    database: punishments
    username: root
    password: password

messaging:
  redis:
    host: localhost
    port: 6379

enable-ban-evade-warnings: true
ban-appeal-link: www.ruinscraft.com
slack-webhook-url: notset
