name: ${name}
version: ${project.version}
main: ${mainClass}
author: royalkingkb
website: https://github.com/Ruinscraft/ruinscraft-punishments
description: Handles punishments for Ruinscraft
load: STARTUP # ensure plugin loads before players join
api-version: 1.13

commands:
  kick:
    description: Kick a player
    permission: punishments.command.kick
  kickip:
    description: Kick an IP address
    permission: punishments.command.kickip
  warn:
    description: Warn a player
    permission: punishments.command.warn
  warnip:
    description: Warn an IP address
    permission: punishments.command.warnip
  mute:
    description: Permanently mute a player
    permission: punishments.command.mute
  muteip:
    description: Permanently mute an IP address
    permission: punishments.command.muteip
  tempmute:
    description: Temporarily mute a player
    permission: punishments.command.tempmute
  tempmuteip:
    description: Temporarily mute an IP address
    permission: punishments.command.tempmuteip
  ban:
    description: Permanently ban a player
    permission: punishments.command.ban
  banip:
    description: Permanently ban an IP address
    permission: punishments.command.banip
  tempban:
    description: Temporarily ban a player
    permission: punishments.command.tempban
  tempbanip:
    description: Temporarily ban an IP address
    permission: punishments.command.tempbanip
  unmute:
    description: Unmute a player
    permission: punishments.command.unmute
  unmuteip:
    description: Unmute an IP address
    permission: punishments.command.unmuteip
  unban:
    description: Unban a player
    permission: punishments.command.unban
  unbanip:
    description: Unban an IP address
    permission: punishments.command.unbanip
  pundo:
    description: Undo the last punishment action on a player
    permission: punishments.command.pundo
  pundoip:
    description: Undo the last punishment action on an IP
    permission: punishments.command.pundoip
  pdel:
    description: Delete a punishment (admin only)
    permission: punishments.command.pdel
  pinfo:
    description: View a player's punishment history
    permission: punishments.command.pinfo
  pinfoip:
    description: View an IP's punishment history
    permission: punishments.command.pinfoip
  addrinfo:
    description: View address logs for a UUID or IP
    permission: punishments.command.addrinfo
